blog.about.companies[0].name=Broadcom
blog.about.companies[0].roles[0].location=Tokyo
blog.about.companies[0].roles[0].period=Dec 2023 \u2013 Present
blog.about.companies[0].roles[0].title=Senior Principal Architect (P6)
blog.about.companies[0].url=https://www.broadcom.com/
blog.about.companies[1].name=VMware
blog.about.companies[1].roles[0].location=Tokyo
blog.about.companies[1].roles[0].period=Aug 2022 \u2013 Dec 2023
blog.about.companies[1].roles[0].title=Senior Staff Cloud Native Architect (P6)
blog.about.companies[1].roles[1].location=Tokyo
blog.about.companies[1].roles[1].period=Apr 2020 \u2013 Jul 2022
blog.about.companies[1].roles[1].title=Staff Cloud Native Architect (P5)
blog.about.companies[1].url=https://vmware.com
blog.about.companies[2].name=Pivotal
blog.about.companies[2].roles[0].location=Tokyo
blog.about.companies[2].roles[0].period=Sep 2018 \u2013 Apr 2020
blog.about.companies[2].roles[0].title=Advisory Solutions Architect (P5)
blog.about.companies[2].roles[1].location=Tokyo
blog.about.companies[2].roles[1].period=Jan 2016 \u2013 Aug 2018
blog.about.companies[2].roles[1].title=Senior Solutions Architect (P4)
blog.about.companies[2].url=https://pivotal.io
blog.about.companies[3].name=NTT DATA
blog.about.companies[3].roles[0].location=Tokyo
blog.about.companies[3].roles[0].period=Apr 2009 \u2013 Dec 2015
blog.about.companies[3].roles[0].title=Assistant Manager
blog.about.companies[3].url=https://www.nttdata.com
blog.about.profile.avatar-url=https://avatars.githubusercontent.com/u/106908?s=200
blog.about.profile.bluesky-handle=ik.am
blog.about.profile.dog-breed-label=Bichon Frise
blog.about.profile.dog-breed-url=https://en.wikipedia.org/wiki/Bichon_Frise
blog.about.profile.dog-name=Lemon
blog.about.profile.email=makingx [at] gmail.com
blog.about.profile.github-handle=making
blog.about.profile.linkedin-slug=toshiaki-maki
blog.about.profile.name=Toshiaki Maki / \u69D9 \u4FCA\u660E
blog.about.profile.title=Senior Principal Architect at Broadcom
blog.about.schools[0].degrees[0].location-label=Graduate School of Information Science and Technology
blog.about.schools[0].degrees[0].location-url=https://www.i.u-tokyo.ac.jp/
blog.about.schools[0].degrees[0].period=Apr 2007 \u2013 Mar 2009
blog.about.schools[0].degrees[0].title=Master of Science, Mechano-Informatics
blog.about.schools[0].degrees[1].location-label=Faculty of Engineering
blog.about.schools[0].degrees[1].location-url=https://www.u-tokyo.ac.jp/
blog.about.schools[0].degrees[1].period=Apr 2003 \u2013 Mar 2007
blog.about.schools[0].degrees[1].title=Bachelor of Science, Mechano-Informatics
blog.about.schools[0].name=The University of Tokyo
blog.api.base-url=https://entry-api.ik.am
blog.api.password=empty
blog.api.username=blog-ui
blog.base-url=https://ik.am
blog.default-og-image=https://raw.githubusercontent.com/categolj/blog-frontend-old/master/blog-frontend-ui/public/ms-icon-310x310.png
blog.description=@making's tech note
blog.giscus.category-id=DIC_kwDOAuF6es4C1OVk
blog.giscus.category=General
blog.giscus.mapping=pathname
blog.giscus.repo-id=MDEwOlJlcG9zaXRvcnk0ODMzMTM4Ng==
blog.giscus.repo=making/blog.ik.am
blog.name=IK.AM
blog.x-handle=@making
counter.api.base-url=http://localhost:8888
counter.api.ip-black-list[0]=127.0.0.1
counter.api.ip-black-list[1]=0:0:0:0:0:0:0:1
logbook.strategy=without-body
logging.level.am.ik.blog.BlogFrontendHtmxApplication=debug
logging.level.io.micrometer.core.instrument.binder.jvm.JvmGcMetrics=error
logging.level.web=info
management.endpoints.web.exposure.include=health,info,prometheus
management.info.env.enabled=true
management.info.git.mode=full
management.info.java.enabled=true
management.info.os.enabled=true
management.logging.export.otlp.enabled=false
management.metrics.distribution.percentiles-histogram.http.client.requests=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.annotations.enabled=true
management.observations.enable.spring.security=false
management.opentelemetry.instrumentation.logback-appender.capture-experimental-attributes=true
management.opentelemetry.instrumentation.logback-appender.capture-key-value-pair-attributes=true
management.opentelemetry.logging.export.otlp.compression=gzip
management.opentelemetry.resource-attributes.git.commit.id.abbrev=${git.commit.id.abbrev:N/A}
management.opentelemetry.tracing.export.otlp.compression=gzip
management.otlp.metrics.export.enabled=false
management.tracing.export.otlp.enabled=false
management.tracing.sampling.probability=1.0
note.api.base-url=https://note-api.ik.am
server.compression.enabled=true
server.compression.mime-types=text/html,text/css,text/xml,text/plain,application/javascript,application/json,application/xml,application/atom+xml
server.compression.min-response-size=1024
server.forward-headers-strategy=native
server.http2.enabled=true
server.port=8081
spring.application.name=blog-frontend
spring.config.import=optional:classpath:git.properties,optional:classpath:META-INF/build-info.properties
spring.mustache.check-template-location=false
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.servlet.expose-session-attributes=true
spring.output.ansi.enabled=always
spring.threads.virtual.enabled=true
spring.web.error.include-message=always
spring.web.error.include-stacktrace=on_param
spring.web.resources.cache.period=365d
spring.web.resources.cache.use-last-modified=false
spring.web.resources.chain.compressed=true
spring.web.resources.chain.strategy.content.enabled=true
